
try:
    10/0
except Exception as x:
    print(f'Nos fue mal porque: {x}')
